version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - dev-network

  handler-service-db:
    restart: always
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=handler_db
    volumes:
      - ./handler/schema:/schema/
    networks:
      - dev-network

  excel-service-db:
    restart: always
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=excel_db
    volumes:
      - ./excel/schema:/schema/
    networks:
      - dev-network

  txt-service-db:
    restart: always
    image: mysql:latest
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=txt_db
    volumes:
      - ./txt/schema:/schema/
    networks:
      - dev-network

#  handler:
#    container_name: handler
#    ports:
#      - "8080:8080"
#    build:
#      context: ./handler
#      dockerfile: /deployments
#    env_file:
#      - ./.env
#    restart: always
#    networks:
#      - dev-network
#    depends_on:
#      - rabbitmq


networks:
  dev-network:
    driver: bridge