version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: forward_recap
      RABBITMQ_DEFAULT_PASS: forward_recap
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - dev-network

  mysql:
    restart: always
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fallbox
    volumes:
      - ./schema:/schema/
    networks:
      - dev-network

  handler:
    container_name: handler
    ports:
      - "8080:8080"
    build:
      context: ./handler
      dockerfile: /deployments
    env_file:
      - ./.env
    restart: always
    networks:
      - dev-network
    depends_on:
      - rabbitmq


networks:
  dev-network:
    driver: bridge