service:
  name: "excel"
  message:
    document_excel_send: "document.excel.send"
    document_excel_get: "document.excel.get"
    document_excel_delete: "document.excel.delete"
rabbitmq:
  host: "localhost"
  port: "5672"
  user: "guest"
  password: "guest"
db:
  host: "localhost"
  port: "3308"
  user: "root"
  password: "root"
  name: "excel_db"
delivery:
  queue:
    durable: true
    auto_delete: false
    exclusive: true
    no_wait: false
  channel:
    auto_ack: true
    exclusive: false
    no_local: false
    no_wait: false
  publish:
    mandatory: false
    immediate: false
  exchange:
    type: "fanout"
    durable: true
    auto_delete: false
    internal: false
    no_wait: false
