service:
  name: "handler"
  message:
    document_png_send: "document.png.send"
    document_png_get: "document.png.get"
    document_excel_send: "document.excel.send"
    document_excel_get: "document.excel.get"
router:
  host: "localhost"
  port: "8080"
  coockie: "handler.jwt"
  auth_path: "/auth"
  png_send_path: "/png/:id/send"
  png_get_path: "/png/:id/get"
  excel_send_path: "/excel/:id/send"
  excel_get_path: "/excel/:id/get"
rabbitmq:
  host: "localhost"
  port: "5672"
  user: "guest"
  password: "guest"
delivery:
  queue:
    durable: true
    auto_delete: false
    exclusive: true
    no_wait: false
  channel:
    auto_ack: true
    exclusive: false
    no_local: false
    no_wait: false
  publish:
    mandatory: false
    immediate: false
  exchange:
    type: "fanout"
    durable: true
    auto_delete: false
    internal: false
    no_wait: false
