service:
  name: "handler"
  message:
    document_png_send: "document.png.send"
    document_png_get: "document.png.get"
    document_png_delete: "document.png.delete"
    document_jpg_send: "document.jpg.send"
    document_jpg_get: "document.jpg.get"
    document_jpg_delete: "document.jpg.delete"
router:
  host: "localhost"
  port: "8080"
  cookie: "handler.jwt"

  auth_path: "/auth"
  registration_path: "/registration"

  get_all_user_png: "/user/:id/png"
  get_user_png: "/user/:id/png/:id"
  post_user_png: "/user/:id/png"
  delete_user_png: "/user/:id/png/:id"

  get_all_user_jpg: "/user/:id/jpg"
  get_user_jpg: "/user/:id/jpg/:id"
  post_user_jpg: "/user/:id/jpg"
  delete_user_jpg: "/user/:id/jpg/:id"
rabbitmq:
  host: "localhost"
  port: "5672"
  user: "guest"
  password: "guest"
db:
  host: "localhost"
  port: "3307"
  user: "root"
  password: "root"
  name: "handler_db"
delivery:
  queue:
    durable: true
    auto_delete: false
    exclusive: true
    no_wait: false
  channel:
    auto_ack: true
    exclusive: false
    no_local: false
    no_wait: false
  publish:
    mandatory: false
    immediate: false
  exchange:
    type: "fanout"
    durable: true
    auto_delete: false
    internal: false
    no_wait: false
