service:
  name: "jpg"
  message:
    document_jpg_send: "document.jpg.send"
    document_jpg_get: "document.jpg.get"
    document_jpg_delete: "document.jpg.delete"
rabbitmq:
  host: "localhost"
  port: "5672"
  user: "guest"
  password: "guest"
db:
  host: "localhost"
  port: "3309"
  user: "root"
  password: "root"
  name: "jpg_db"
delivery:
  queue:
    durable: true
    auto_delete: false
    exclusive: true
    no_wait: false
  channel:
    auto_ack: true
    exclusive: false
    no_local: false
    no_wait: false
  publish:
    mandatory: false
    immediate: false
  exchange:
    type: "fanout"
    durable: true
    auto_delete: false
    internal: false
    no_wait: false
